module.exports = {
  up: `
  CREATE TABLE partner( email VARCHAR(40)PRIMARY KEY, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
    `,
  down: 'DROP TABLE partner;'
};
